#!/bin/bash
cd ./platforms/browser/www
rsync --exclude=assets/header.js -avz --delete  . "gabriel@newton.eycproveedores.com:htdocs/logistica/web"
rsync --exclude=assets/header.js -avz --delete  . "gabriel@newton.eycproveedores.com:htdocs/logistica2/web"
echo "syncronized"
cd ../../../
